/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.aquarae.netty.client;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        EchoClient classUnderTest = new EchoClient();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
